# Usage examples:
#
# 1. Building
#   - avatar2-core-arm and avatar2-arm images
#     $ docker compose build
#   - a single image
#     $ docker compose build avatar2-core-arm
#   - the test profile
#     $ docker compose --profile test build
#
# 2. Running
#   - By default, ipython3 shell is started
#     $ docker compose run --rm avatar2-arm
#   - To start a bash shell
#     $ docker compose run --rm avatar2-arm bash
#   - Bind the working directory inside the container and start a shell
#     $ docker compose run -i --rm -v $(pwd):/avatar2 avatar2-arm bash
#   - Launch the tests
#     $ docker compose run --rm tests-arm
#

x-common-options: &common-options
    command: /usr/bin/ipython3
    stdin_open: true
    tty: true
    privileged: true
    volumes:
        - /run/udev:/run/udev:ro
        - /dev/bus:/dev/bus:ro
        #- .:/workspace:rw
    entrypoint: []

x-avatar2-core: &avatar2-core
    image: avatartwo/avatar2-core
    build:
        dockerfile: docker/avatar2-core.Dockerfile
        context: .

x-avatar2: &avatar2
    image: avatartwo/avatar2
    build:
        dockerfile: docker/avatar2.Dockerfile
        context: .

#x-avatar2-panda: &avatar2-panda
#    image: avatartwo/avatar2-panda
#    build:
#        dockerfile: docker/avatar2-panda.Dockerfile
#        context: .

x-tests: &tests
    image: avatartwo/tests
    build:
        dockerfile: docker/tests.Dockerfile
        context: .

 
services:

    avatar2-arm:
        <<: [*avatar2, *common-options]
        depends_on:
          - avatar2-core-arm
        environment:
            AVATAR2_ARCH: ARM
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-arm

    avatar2-mips:
        <<: [*avatar2, *common-options]
        depends_on:
          - avatar2-core-mips
        environment:
            AVATAR2_ARCH: MIPS
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-mips

    avatar2-i386:
        <<: [*avatar2, *common-options]
        depends_on:
          - avatar2-core-i386
        environment:
            AVATAR2_ARCH: X86
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-i386

    avatar2-x86:
        <<: [*avatar2, *common-options]
        depends_on:
          - avatar2-core-x86
        environment:
            AVATAR2_ARCH: X86
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-x86_64

# (WIP) With PANDA
#    avatar2-panda-arm:
#        <<: [*avatar2-panda, *common-options]
#        environment:
#            AVATAR2_ARCH: ARM
#            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
#            AVATAR2_QEMU_EXECUTABLE: qemu-system-arm
#            AVATAR2_PANDA_EXECUTABLE: panda-system-arm
#
#    avatar2-panda-mips:
#        <<: [*avatar2-panda, *common-options]
#        environment:
#            AVATAR2_ARCH: MIPS
#            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
#            AVATAR2_QEMU_EXECUTABLE: qemu-system-mips
#            AVATAR2_PANDA_EXECUTABLE: panda-system-mips
#
#    avatar2-panda-x86:
#        <<: [*avatar2-panda, *common-options]
#        environment:
#            AVATAR2_ARCH: X86
#            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
#            AVATAR2_QEMU_EXECUTABLE: qemu-system-x86_64
#            AVATAR2_PANDA_EXECUTABLE: panda-system-x86_64

# Lightweight images without qemu
    avatar2-core-arm:
        <<: [*avatar2-core, *common-options]
        environment:
            AVATAR2_ARCH: ARM
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch

    avatar2-core-mips:
        <<: [*avatar2-core, *common-options]
        environment:
            AVATAR2_ARCH: MIPS
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch

    avatar2-core-i386:
        <<: [*avatar2-core, *common-options]
        environment:
            AVATAR2_ARCH: X86
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch

    avatar2-core-x86:
        <<: [*avatar2-core, *common-options]
        environment:
            AVATAR2_ARCH: X86
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch

# Tests
    tests-arm:
        <<: [*tests, *common-options]
        profiles: ["test"]
        depends_on:
          - avatar2-arm
        environment:
            AVATAR2_ARCH: ARM
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-arm
        command: python3 -m pytest /avatartwo/avatar2/tests -v

    tests-mips:
        <<: [*tests, *common-options]
        profiles: ["test"]
        depends_on:
          - avatar2-mips
        environment:
            AVATAR2_ARCH: MIPS
            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
            AVATAR2_QEMU_EXECUTABLE: qemu-system-mips
        command: python3 -m pytest /avatartwo/avatar2/tests -v
#
#    tests-i386:
#        <<: [*tests, *common-options]
#        profiles: ["test"]
#        depends_on:
#          - avatar2-i386
#        environment:
#            AVATAR2_ARCH: X86
#            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
#            AVATAR2_QEMU_EXECUTABLE: qemu-system-i386
#        command: python3 -m pytest /avatartwo/avatar2/tests -v
#
#    tests-x86:
#        <<: [*tests, *common-options]
#        profiles: ["test"]
#        depends_on:
#          - avatar2-x86
#        environment:
#            AVATAR2_ARCH: X86
#            AVATAR2_GDB_EXECUTABLE: gdb-multiarch
#            AVATAR2_QEMU_EXECUTABLE: qemu-system-x86_64
#        command: python3 -m pytest /avatartwo/avatar2/tests -v

