name: Build avatar2 and its targets

on: 
    push: 
        branches:
            - 'main'
            - 'dev/*'
    pull_request:
        branches:
            - 'main'
            - 'dev/*'


jobs:
    build:
        if: github.repository == 'avatartwo/avatar2'
        runs-on: ubuntu-20.04
        steps:
            - name: Install dependencies
              run: |
                apt-get update
                apt-get upgrade -y
                apt-get install -y -m -f --install-suggests python3 python3-pip python3-setuptools python3-dev cmake build-essential libcapstone3 libcapstone-dev
                apt-get install -y -m -f --install-suggests
                pip3 install --upgrade pip
                pip3 install nose2

            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Build avatar2
              run: |
                cd ${{ github.workspace }}
                python3 setup.py install

            - name: Install debuggers targets
              run: |
                apt-get install -y -m -f --install-suggests gdb gdb-multiarch openocd

            - name: Build avatar-qemu target
              run: |
                cd ${{ github.workspace }}/targets
                echo yes | ./build_qemu.sh

            - name: Run unit tests
              run: |
                cd ${{ github.workspace }}
                python3 ./tests/hello_world.py
                python3 ./tests/gdb_memory_map_loader.py
                nose2 -v

