name: Build avatar2 and its targets

on: 
    push: 
        branches:
            - 'main'
            - 'dev/*'
    pull_request:
        branches:
            - 'main'
            - 'dev/*'


jobs:
    build:
        if: github.repository == 'avatartwo/avatar2'
        runs-on: ubuntu-20.04
        steps:
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get upgrade -y
                sudo apt-get install -y -m -f --install-suggests python3 python3-pip python3-setuptools python3-dev cmake build-essential git libcapstone3 libcapstone-dev
                pip3 install --upgrade pip
                pip3 install nose2

            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Build avatar2
              run: |
                cd ${{ github.workspace }}
                sudo python3 setup.py install

            - name: Install debuggers targets
              run: |
                sudo apt-get install -y -m -f --install-suggests gdb gdb-multiarch openocd

            - name: Build avatar-qemu target
              run: |
                cd ${{ github.workspace }}/targets
                echo yes | ./build_qemu.sh

            - name: Build panda target
              run: |
                git clone https://github.com/panda-re/panda.git
                cd panda
                git checkout 5fb8a5098d0647a13e5e7d39d20ff9f04242572d
                sudo ./panda/scripts/install_ubuntu.sh

            - name: Run unit tests
              env: 
                AVATAR2_ARCH: ARM
                AVATAR2_GDB_EXECUTABLE: gdb-multiarch
              run: |
                cd ${{ github.workspace }}
                python3 ./tests/hello_world.py
                python3 ./tests/gdb_memory_map_loader.py

            - name: Run unit tests for ARM
              env: 
                AVATAR2_ARCH: ARM
                AVATAR2_GDB_EXECUTABLE: gdb-multiarch
                AVATAR2_QEMU_EXECUTABLE: qemu-system-arm
                AVATAR2_PANDA_EXECUTABLE: panda-system-arm
              run: |
                cd ${{ github.workspace }}
                nose2 -v

            - name: Run unit tests for MIPS
              env: 
                AVATAR2_ARCH: MIPS
                AVATAR2_GDB_EXECUTABLE: gdb-multiarch
                AVATAR2_QEMU_EXECUTABLE: qemu-system-mips
                AVATAR2_PANDA_EXECUTABLE: panda-system-mips
              run: |
                cd ${{ github.workspace }}
                nose2 -v

