name: CI

on: 
    push: 
        branches:
            - 'main'
            - 'dev**'
    pull_request:
        branches:
            - 'main'
            - 'dev**'
    workflow_dispatch:      # allow manual trigger


jobs:
    build:
        name: Building avatar2 docker images
        if: github.repository == 'avatartwo/avatar2'
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build with docker compose
              run: |
                docker compose build

            - name: Save docker images
              run: |
                mkdir -p /tmp/avatar2-docker-images
                docker save avatartwo/avatar2-core:latest -o /tmp/avatar2-docker-images/avatar2-core.tar
                docker save avatartwo/avatar2:latest -o /tmp/avatar2-docker-images/avatar2.tar

            - name: Upload docker images as artifacts
              uses: actions/upload-artifact@v4
              with:
                name: avatar2-docker-images
                path: /tmp/avatar2-docker-images/
                retention-days: 30
                #compression-level: 9
                overwrite: true

    test:
        name: Unit Testing
        needs: build
        runs-on: ubuntu-24.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Download docker images artifacts
              uses: actions/download-artifact@v4
              with:
                name: avatar2-docker-images
                path: /tmp/avatar2-docker-images/

            - name: Load docker images
              run: |
                docker load -i /tmp/avatar2-docker-images/avatar2-core.tar
                docker load -i /tmp/avatar2-docker-images/avatar2.tar

            - name: Build test profile docker image
              run: |
                docker compose --profile test build

            - name: Run unit tests for ARM
              run: docker compose run --rm tests-arm

            - name: Run unit tests for MIPS
              run: docker compose run --rm tests-mips
